#sudo: false

language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update


install:


before_script:


script:
  - cd $TRAVIS_BUILD_DIR/tests
  - phpunit

after_script:
