sudo: false

language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

script:
  - phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover.xml; fi;'
