sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - composer self-update

script:
  - phpunit

after_script:
  # Scrutinizer-CI.
  # PHP 7-dev does not support xDebug, so phpUnit can not produce a coverage
  # report. We ignore sending the coverage report for PHP 7.
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
