sudo: false

language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

addons:
  code_climate:
    repo_token: a19d7e5ebdda6dce8fe813ceec06b452bf7edc562dff69c0ad42e073f74db7cf

before_install:
  - composer self-update
  - composer install

install:


before_script:


script:
  - phpunit

after_script:
  # Send code coverage to Code Climate
  - vendor/bin/test-reporter
